---
- name: Deploy VC and Hosts
  hosts: localhost
  gather_facts: False
  become: true
  # vars_files:
  #   - ../answerfile.yml
  pre_tasks:
  #   - name: Ensure fuseiso is intalled
  #     package:
  #       name: fuseiso
  #       state: present
    - name: Ensure xorriso is installed
      package:
        name: xorriso
        state: present  
  tasks:
    - name: Check if vCenter already exists so install steps can be skipped
      uri:
        url: "https://{{ vcenter.ip }}/ui/"
        method: GET
        status_code: 200
        timeout: 2
        validate_certs: False
      ignore_errors: True
      register: vcenter_response

    - set_fact:
        vcenter_exists={{vcenter_response.status == 200}}

    # - name: Mount VC installer
    #   action: mount name='{{tmp_dir}}/VCSA' src="{{ vcIso }}" opts=loop fstype=iso9660 state=mounted
    #   tags: mount
    #   when: not vcenter_exists

    # - name: Create VCSA ISO Directory
    #   file:
    #     path: '{{tmp_dir}}/VCSA'
    #     state: directory
    
    # - name: Ensure mount point is empty in case of previous failed runs
    #   command: fusermount -u {{tmp_dir}}/VCSA
    #   ignore_errors: yes

    # - name: Mount VC Install with Fuse ISO
    #   command: fuseiso {{vcIso}} {{tmp_dir}}/VCSA

    - name: Fix permissions before delete
      command: chmod -R +w {{tmp_dir}}/VCSA
      ignore_errors: yes

    - name: Clean ESX ISO Directory
      file:
        path: '{{tmp_dir}}/VCSA'
        state: absent

    - name: Extract ISO image
      command: xorriso -ecma119_map lowercase -osirrox on -indev {{vcIso}} -extract / {{tmp_dir}}/VCSA

    - name: Fix permissions
      command: "{{item}}"
      with_items:
        - chmod -R 777 {{tmp_dir}}/VCSA
        # - find {{tmp_dir}}/VCSA -type f -exec chmod -c 0644 {} \;

    - name: Create JSON template file for VCSA 6.5 with embeded PSC
      template: 
        src=../templates/embedded_vCSA_on_VC_6.5.json
        dest={{tmp_dir}}/vCSA_on_ESXi.json
      when: vcIso is search("-6.5.") and not vcenter_exists
    
    - name: Create JSON template file for VCSA 6.7 with embeded PSC
      template: 
        src=../templates/embedded_vCSA_on_VC_6.7.json
        dest={{tmp_dir}}/vCSA_on_ESXi.json
      when: vcIso is search("-6.7.") and not vcenter_exists

    - name: Perform VC CLI Install
      command: "./vcsa-deploy install --accept-eula --no-esx-ssl-verify {{tmp_dir}}/vCSA_on_ESXi.json"
      args:
        chdir: '{{tmp_dir}}/VCSA/vcsa-cli-installer/lin64/'
      when: not vcenter_exists
      async: 3600
      poll: 0
      register: vcenter_result

    - name: Deploy Nested vESXi VMs
      nestedESXi:
        vcenter: "{{ vc_mng.ip }}"
        vmname: "{{ environment_tag }}-{{ item.key }}"
        vcenter_user: "{{ vc_mng.user }}" 
        vcenter_passwd: "{{ vc_mng.password }}" 
        cluster: "{{ item.value.mng_cluster }}"
        datastore: "{{ vc_mng.datastore }}" 
        vmk_portgroup: "{{ item.value.vmk_portgroup}}" 
        tep_portgroup: "{{ item.value.tep_portgroup}}" ### Must be attached to port group with MTU of 1600+
        cpucount: "{{ item.value.cpu }}"
        memory: "{{ item.value.ram }}"
        hdd: "{{ item.value.hdd }}"
        isopath: "ESXI-ISO/customesxv.iso"
      with_dict: "{{ vESX }}"
      async: 7200
      poll: 0
      register: hosts

    - name: Wait 5 seconds before start checking wheter the hosts are ready
      pause: seconds=5

    - name: Result check for deployment of host
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      with_items: "{{ hosts.results }}"
      retries: 100
      delay: 15

    - debug: msg="The vCenter deployment can take a long time.\nYou can check progress at https://{{vcenter.ip}}:5480 after about 20 minutes.\nFor detailed output browse to the most recent folder starting with vcsaCliInstaller under {{tmp_dir}} and follow vcsa-cli-installer.log "
      when: not vcenter_exists

    - name: Result check for deployment of vCenter task
      async_status:
        jid: "{{ vcenter_result.ansible_job_id }}"
      register: job_result
      until: job_result.finished      
      retries: 240
      delay: 15
      when: not vcenter_exists

    - name: Check the vSphere API is online
      command: "curl -k --silent -v https://{{ vcenter.ip }}/ui/"
      register: result
      until: result.stdout.find("<title>vSphere Client</title>") != -1
      retries: 120
      delay: 5
      changed_when: false
      when: not vcenter_exists

    - name: Wait 30 seconds for the vCenter to settle
      pause: seconds=30
      when: not vcenter_exists

    
    
    - name: Create Datacenter
      vmware_datacenter:
        hostname: "{{ vcenter.ip }}"
        username: "administrator@vsphere.local"
        password: "{{ vcenter.password }}"
        datacenter_name: "{{ vcenter.datacenter }}"
        state: present
        validate_certs: False
        
    - name: Create Clusters
      vmware_cluster:
        hostname: "{{ vcenter.ip }}"
        username: "{{ vcenter.user }}"
        password: "{{ vcenter.password }}"
        datacenter_name: "{{ vcenter.datacenter }}"
        cluster_name: "{{ item.key }}"
        validate_certs: False
        enable_ha: False  # Hardcoded as we need to enable HA after vSAN is enabled and disks are claimed
        enable_drs: "{{ item.value.drs }}"
        enable_vsan: False  # Hardcoded as we need to enable vSAN when the hosts are added to the cluster
      with_dict: "{{ clusters }}"

  post_tasks:
    - name: Unmount VCSA installer
      action: mount name='{{tmp_dir}}/VCSA' src="{{ vcIso }}" fstype=iso9660 state=absent
      when: not vcenter_exists
    
    # - name: Unmount VSCA install with fuse
    #   command: fusermount -u {{tmp_dir}}/VCSA
    #   ignore_errors: yes

    # - name: Clean VCSA ISO Directory
    #   file:
    #     path: '{{tmp_dir}}/VCSA/'
    #     state: absent

    - name: Delete the temporary JSON template file
      file: 
        path: '{{tmp_dir}}/vCSA_on_ESXi.json' 
        state: absent

    - name: Clean ESX ISO Directory
      file:
        path: '{{tmp_dir}}/VCSA/'
        state: absent
