---
- name: Prepare ESXi installer ISO
  hosts: localhost
  gather_facts: False
  pre_tasks:
    - name: Ensure xorriso is intalled
      package:
        name: xorriso
        state: present

  tasks:    
    
    - name: Fix permissions before delete
      command: chmod -R +w {{tmp_dir}}/ESX
      ignore_errors: yes

    - name: Clean ESX ISO Directory
      file:
        path: '{{tmp_dir}}/ESX'
        state: absent

    - name: Extract ISO image
      command: xorriso -ecma119_map lowercase -osirrox on -indev {{esxIso}} -extract / {{tmp_dir}}/ESX

    - name: Fix permissions
      command: "{{item}}"
      with_items:
        - chmod 777 {{tmp_dir}}/ESX
        - find {{tmp_dir}}/ESX -type f -exec chmod -c 0644 {} \;

    - name: Edit boot.cfg for pre 6.7
      replace:
        dest: '{{tmp_dir}}/ESX/boot.cfg'
        regexp: 'kernelopt=runweasel'
        replace: 'kernelopt=ks=cdrom:/KS.CFG'

    - name: Edit boot.cfg for post 6.7
      replace:
        dest: '{{tmp_dir}}/ESX/boot.cfg'
        regexp: 'kernelopt=cdromBoot runweasel'
        replace: 'kernelopt=cdromBoot ks=cdrom:/KS.CFG'

    - name: Create empty KS file
      file:
        path: '{{tmp_dir}}/ESX/KS.CFG'
        state: touch

    - name: Update KS file
      blockinfile:
        path: '{{tmp_dir}}/ESX/KS.CFG'
        block: |
          vmaccepteula
          rootpw {{nested_host_credentials.password}}
          install --firstdisk --overwritevmfs
          network --bootproto=dhcp --device=vmnic0 --addvmportgroup=0
          reboot

          %firstboot --interpreter=busybox
          vim-cmd hostsvc/enable_ssh
          vim-cmd hostsvc/start_ssh
          vim-cmd hostsvc/enable_esx_shell
          vim-cmd hostsvc/start_esx_shell

    - name: Burn an ISO image
      command: xorrisofs -relaxed-filenames -J -R -o {{tmp_dir}}/customesxv.iso -b isolinux.bin -c boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table {{tmp_dir}}/ESX/
      args:
        chdir: '{{tmp_dir}}/ESX/'

    - name: Upload the ISO to the Datastore
      vsphere_copy: host="{{ parent_vcenter.ip }}" login="{{ parent_vcenter.user }}" password="{{ parent_vcenter.password }}" src={{tmp_dir}}/customesxv.iso datacenter="{{ parent_vcenter.datacenter }}" datastore="{{ parent_vcenter.datastore }}" path=/ESXI-ISO/custom-esx-{{vsphere_version}}.iso validate_certs=False
      tags: upload

  post_tasks:
    - name: Clean ESX ISO Directory
      file:
        path: '{{tmp_dir}}/ESX/'
        state: absent
    - name: Clean KS temp dir path
      file:
        state: absent
        path: "{{tmp_dir}}/ks-esxi/"